# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_seq_model": "00_seq.ipynb",
         "featurize_context": "00_seq.ipynb",
         "predict_seq": "00_seq.ipynb"}

modules = ["seq.py"]

doc_url = "https://gpp-rnd.github.io/rs3/"

git_url = "https://github.com/gpp-rnd/rs3/tree/master/"

def custom_doc_links(name): return None
