# AUTOGENERATED! DO NOT EDIT! File to edit: 00_seq.ipynb (unless otherwise specified).

__all__ = ['load_seq_model', 'featurize_context', 'predict_seq']

# Cell
import joblib
import sglearn
import pandas as pd

# Cell
def load_seq_model():
    """Load rule set 3 sequence model"""
    model = joblib.load('RuleSet3.pkl')
    return model

# Cell
def featurize_context(context_sequences):
    """Featurize context sequences

    :param context_sequences: list-like
    :return: DataFrame, feature matrix
    """
    context_series = pd.Series(context_sequences)
    if not (context_series.str.len() == 30).all():
        raise  ValueError('All context sequences must be 30 nucleotides')
    featurized_sgrnas = sglearn.featurize_guides(context_sequences)
    return featurized_sgrnas

# Cell
def predict_seq(context_sequences):
    """Predict the activity of context sequence for SpCas9 Knockout using sequence information only

    :param context_sequences: list of str
    :return: list of float, predictions
    """
    model = load_seq_model()
    featurized_sgrnas = featurize_context(context_sequences)
    seq_predictions = model.predict(featurized_sgrnas)
    return seq_predictions